name: rolling_nav_bar
description: A Flutter nav bar with a rolling active indicator behind each icon
version: 0.0.3
homepage: https://github.com/craiglabenz/flutter_rolling_nav_bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  badges: ^1.1.0
  polygon_clipper: ^1.0.2
  tinycolor: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
